In [1]:
import numpy as np

In [2]:
def softmax(x):
    exponents=np.exp(x)
    return exponents/np.sum(exponents)

In [3]:
out=np.array([1,2,3])
softmax(out),sum(softmax(out))

(array([0.09003057, 0.24472847, 0.66524096]), 1.0)

In [4]:
output_of_layer_2=np.array([12,34,-67,23,0,134,76,24,78,-98])
a=softmax(output_of_layer_2)
a,sum(a)

(array([1.03770332e-053, 3.72007598e-044, 5.09107081e-088, 6.21315959e-049,
        6.37586958e-059, 1.00000000e+000, 6.47023493e-026, 1.68891188e-048,
        4.78089288e-025, 1.75258947e-101]),
 1.0)

In [5]:
x=np.argmax(a)
x,output_of_layer_2[x]

(5, 134)

In [8]:
import jovian
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "karynaur/softmax-example" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..


[jovian] Error: Failed to read Anaconda environment using command: "conda env export -n base --no-builds"
[jovian] Error: Failed to read pip environment using command: "pip --disable-pip-version-check freeze"


[jovian] Committed successfully! https://jovian.ai/karynaur/softmax-example


'https://jovian.ai/karynaur/softmax-example'

In [7]:
a=[1000]
softmax(a)

<ipython-input-2-09e1656b02dc>:2: RuntimeWarning: overflow encountered in exp
  exponents=np.exp(x)
<ipython-input-2-09e1656b02dc>:3: RuntimeWarning: invalid value encountered in true_divide
  return exponents/np.sum(exponents)


array([nan])

In [ ]:
targets = np.zeros((len(y),10), np.float32)
targets[range(targets.shape[0]),y] = 1

In [ ]:
x_l1=x.dot(l1)
x_sigmoid=sigmoid(x_l1)
x_l2=x_sigmoid.dot(l2)
out=softmax(x_l2)

In [ ]:
error=2*(out-targets)/out.shape[0]*d_softmax(x_l2)

In [ ]:
update_l2=x_sigmoid.T@error

In [ ]:
error=((l2).dot(error.T)).T*d_sigmoid(x_l1)

In [ ]:
update_l1=x.T@error